/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TresEnRaya;

import javax.swing.JOptionPane;

/**
 *
 * @author FP
 */
public class Interfaz extends javax.swing.JFrame {

    Tablero t = new Tablero();

    public Interfaz() {
        t.iniciarTablero();
        t.vissualizar();
        initComponents();
    }

    /**
     * Creates new form Interfaz
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("un"
            + "checked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        boton1 = new javax.swing.JToggleButton();
        boton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();
        jToggleButton7 = new javax.swing.JToggleButton();
        jToggleButton8 = new javax.swing.JToggleButton();
        jToggleButton9 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(3, 3));

        boton1.setFont(new java.awt.Font("Snap ITC", 0, 24)); // NOI18N
        boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton1ActionPerformed(evt);
            }
        });
        jPanel1.add(boton1);

        boton2.setFont(new java.awt.Font("Snap ITC", 0, 24)); // NOI18N
        boton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton2ActionPerformed(evt);
            }
        });
        jPanel1.add(boton2);

        jToggleButton3.setFont(new java.awt.Font("Snap ITC", 0, 24)); // NOI18N
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton3);

        jToggleButton4.setFont(new java.awt.Font("Snap ITC", 0, 24)); // NOI18N
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton4);

        jToggleButton5.setFont(new java.awt.Font("Snap ITC", 0, 24)); // NOI18N
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton5);

        jToggleButton6.setFont(new java.awt.Font("Snap ITC", 0, 24)); // NOI18N
        jToggleButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton6);

        jToggleButton7.setFont(new java.awt.Font("Snap ITC", 0, 24)); // NOI18N
        jToggleButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton7);

        jToggleButton8.setFont(new java.awt.Font("Snap ITC", 0, 24)); // NOI18N
        jToggleButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton8);

        jToggleButton9.setFont(new java.awt.Font("Snap ITC", 0, 24)); // NOI18N
        jToggleButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton9);

        jLabel1.setText("Jugador 1");

        jLabel2.setText("Jugador 2");

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel3.setText("X");

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel4.setText("O");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton1ActionPerformed
        if (t.geTurno()) {
            if (boton1.getText().isEmpty()) {
                boton1.setText("X");
            }

        } else {
            if (boton1.getText().isEmpty()) {
                boton1.setText("O");
            }
        }

        t.ponerFicha(0, 0);
        t.vissualizar();
        if (t.haGanado("X")) {
            System.out.println("ha ganado el jugador X");
            t.iniciarTablero();
            
        }if(t.haGanado("O")){
            System.out.println("ha ganado el jugador O");
            t.iniciarTablero();
        }
    }//GEN-LAST:event_boton1ActionPerformed

    private void boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton2ActionPerformed
        if (t.geTurno()) {
            if (boton2.getText().isEmpty()) {
                boton2.setText("X");
            }
        } else {
            if (boton2.getText().isEmpty()) {
                boton2.setText("O");
            }
        }
        t.ponerFicha(0, 1);
        t.vissualizar();
        if (t.haGanado("X")) {
            System.out.println("ha ganado el jugador X");
            t.iniciarTablero();
            
        }if(t.haGanado("O")){
            System.out.println("ha ganado el jugador O");
            t.iniciarTablero();
        }
    }//GEN-LAST:event_boton2ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        if (t.geTurno()) {
            if (jToggleButton3.getText().isEmpty()) {
                jToggleButton3.setText("X");
            }

        } else {
            if (jToggleButton3.getText().isEmpty()) {
                jToggleButton3.setText("O");
            }
        }
        t.ponerFicha(0, 2);
        t.vissualizar();
        if (t.haGanado("X")) {
            System.out.println("ha ganado el jugador X");
            t.iniciarTablero();
            
        }if(t.haGanado("O")){
            System.out.println("ha ganado el jugador O");
            t.iniciarTablero();
        }
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        if (t.geTurno()) {
            if (jToggleButton4.getText().isEmpty()) {

                jToggleButton4.setText("X");
            }
        } else {
            if (jToggleButton4.getText().isEmpty()) {
                jToggleButton4.setText("O");
            }
        }
        t.ponerFicha(1, 0);
        t.vissualizar();
        if (t.haGanado("X")) {
            System.out.println("ha ganado el jugador X");
            t.iniciarTablero();
            
        }if(t.haGanado("O")){
            System.out.println("ha ganado el jugador O");
            t.iniciarTablero();
        }
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
        if (t.geTurno()) {
            if (jToggleButton5.getText().isEmpty()) {
                jToggleButton5.setText("X");
            }

        } else {
            if (jToggleButton5.getText().isEmpty()) {
                jToggleButton5.setText("O");
            }
        }
        t.ponerFicha(1, 1);
        t.vissualizar();
        if (t.haGanado("X")) {
            System.out.println("ha ganado el jugador X");
            t.iniciarTablero();
            
        }if(t.haGanado("O")){
            System.out.println("ha ganado el jugador O");
            t.iniciarTablero();
        }
    }//GEN-LAST:event_jToggleButton5ActionPerformed

    private void jToggleButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton6ActionPerformed
        if (t.geTurno()) {
            if (jToggleButton6.getText().isEmpty()) {

                jToggleButton6.setText("X");
            }
        } else {
            if (jToggleButton6.getText().isEmpty()) {

                jToggleButton6.setText("O");
            }

        }
        t.ponerFicha(1, 2);
        t.vissualizar();
        if (t.haGanado("X")) {
            System.out.println("ha ganado el jugador X");
            t.iniciarTablero();
            
        }if(t.haGanado("O")){
            System.out.println("ha ganado el jugador O");
            t.iniciarTablero();
        }
    }//GEN-LAST:event_jToggleButton6ActionPerformed

    private void jToggleButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton7ActionPerformed
        if (t.geTurno()) {
            if (jToggleButton7.getText().isEmpty()) {
                jToggleButton7.setText("X");
            }

        } else {
            if (jToggleButton7.getText().isEmpty()) {

                jToggleButton7.setText("O");
            }
        }
        t.ponerFicha(2, 0);
        t.vissualizar();
        if (t.haGanado("X")) {
            System.out.println("ha ganado el jugador X");
            t.iniciarTablero();
            
        }if(t.haGanado("O")){
            System.out.println("ha ganado el jugador O");
            t.iniciarTablero();
        }
    }//GEN-LAST:event_jToggleButton7ActionPerformed

    private void jToggleButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton8ActionPerformed
        if (t.geTurno()) {
            if (jToggleButton8.getText().isEmpty()) {
                jToggleButton8.setText("X");
            }

        } else {
            if (jToggleButton8.getText().isEmpty()) {
                jToggleButton8.setText("O");
            }
        }
        t.ponerFicha(2, 1);
        t.vissualizar();
        if (t.haGanado("X")) {
            System.out.println("ha ganado el jugador X");
            t.iniciarTablero();
            
        }if(t.haGanado("O")){
            System.out.println("ha ganado el jugador O");
            t.iniciarTablero();
        }
    }//GEN-LAST:event_jToggleButton8ActionPerformed

    private void jToggleButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton9ActionPerformed
        if (t.geTurno()) {
            if (jToggleButton9.getText().isEmpty()) {

                jToggleButton9.setText("X");
            }
        } else {
            if (jToggleButton9.getText().isEmpty()) {

                jToggleButton9.setText("O");
            }
        }
        t.ponerFicha(2, 2);
        t.vissualizar();
        if (t.haGanado("X")) {
            System.out.println("ha ganado el jugador X");
            t.iniciarTablero();
            
        }
    }//GEN-LAST:event_jToggleButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        Tablero t = new Tablero();
        t.iniciarTablero();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton boton1;
    private javax.swing.JToggleButton boton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JToggleButton jToggleButton9;
    // End of variables declaration//GEN-END:variables
}
